-- AlterTable
ALTER TABLE "Trade" ALTER COLUMN "expirationDate" SET DATA TYPE DATE,
ALTER COLUMN "closedAt" SET DATA TYPE DATE,
ALTER COLUMN "createdAt" SET DEFAULT CURRENT_DATE,
ALTER COLUMN "createdAt" SET DATA TYPE DATE;
